apiVersion: v1
data:
  ca-key: |+
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
    NhAAAAAwEAAQAAAgEA2WDlOgHhfAvNB9f8m4TolqXBrFSFsCiqE2S/EOL4rFkBbZxPL1Fa
    POKN6u5Bsblrcgj4PNpStPSnpZwBBRr6u4cCPOgI0LzV0sF6eO07L3TnYOuds8/712fJ/c
    ZHWthnP0mNGpAmYYd+qEFwjKxVS8Zar5EFE1zLZQfWKqosTo2Fig1mXyDjgTJViaTT0WEI
    Y8tjD8zFaGBgiVnjGHm1NAulxe5t+cTCb6ypw/CBUsn0wPHj/qm83wAULkfT0BFRDnSipr
    VBnDfTT1Gzjr8SyXrKluJfL/MTvTHlFQJ3mj3EDdTIRF297lAk31IVmt6itHrEbp+ZfgW5
    GRqk9UC2q5d+M0nOHpyXCzzSFFPHTpglM3HGzOT4+LHL5Lnplvlo6DUFG8chiI3bUtcO2J
    S6RqsRd6cia92iFAw7Ym+vQnejXmgaQL4o2DizcqdPh0Ko1VpKIqltXDC7Q7RCgTvRqQEu
    5izwPVLiUeXzYxKaKhRTk/vlNH5imUG0R+rsRkCku20POWR8OT4eQMfbfDYQ25UWHQuhiL
    MCr78opx/y5ZVJ4845g021vnZMFZM5JzFYeV7nhrudDaIZEGqQF7ikOjGjdbofUtbuI5Wy
    +VRFZlE4Pqu0lEd8xGpx5ew05yxTbjUhZEsoVl4wYPgJVVCiIoEyaQKcuNWrQztCPW501x
    sAAAdAKyZfVCsmX1QAAAAHc3NoLXJzYQAAAgEA2WDlOgHhfAvNB9f8m4TolqXBrFSFsCiq
    E2S/EOL4rFkBbZxPL1FaPOKN6u5Bsblrcgj4PNpStPSnpZwBBRr6u4cCPOgI0LzV0sF6eO
    07L3TnYOuds8/712fJ/cZHWthnP0mNGpAmYYd+qEFwjKxVS8Zar5EFE1zLZQfWKqosTo2F
    ig1mXyDjgTJViaTT0WEIY8tjD8zFaGBgiVnjGHm1NAulxe5t+cTCb6ypw/CBUsn0wPHj/q
    m83wAULkfT0BFRDnSiprVBnDfTT1Gzjr8SyXrKluJfL/MTvTHlFQJ3mj3EDdTIRF297lAk
    31IVmt6itHrEbp+ZfgW5GRqk9UC2q5d+M0nOHpyXCzzSFFPHTpglM3HGzOT4+LHL5Lnplv
    lo6DUFG8chiI3bUtcO2JS6RqsRd6cia92iFAw7Ym+vQnejXmgaQL4o2DizcqdPh0Ko1VpK
    IqltXDC7Q7RCgTvRqQEu5izwPVLiUeXzYxKaKhRTk/vlNH5imUG0R+rsRkCku20POWR8OT
    4eQMfbfDYQ25UWHQuhiLMCr78opx/y5ZVJ4845g021vnZMFZM5JzFYeV7nhrudDaIZEGqQ
    F7ikOjGjdbofUtbuI5Wy+VRFZlE4Pqu0lEd8xGpx5ew05yxTbjUhZEsoVl4wYPgJVVCiIo
    EyaQKcuNWrQztCPW501xsAAAADAQABAAACACYUxHOCCtdpVdTO8LDp+rkRdrlS4Uy4Avt8
    xcAWkwvWV9q07GZUsSNDaStD6/xPiFQk4CAA+0Y6KfhoOQGE9XHOuASlfY3b1vWh8Wun25
    t3tmUTQcBTakIVK5yqlKuEh6ndn7uMjzy8uOKO/EGYmyS4LgDdve7jbbpYQhudTj/AqSlD
    KbD2mQR0JeoEFxtyDT82TTdiXx7m62KEfbU29RiWBceD+n4sCwf3TpJF2tH/EUKP3aoqYC
    0M3XwyFxg3QGTw5+GelUzhtsIJhRQ3wvnK6hy+sYA77DRTvlcM5Jj/ww3NPfxEE9bg8WSy
    A5jq8cP+UdUzXndmV0PfmBBi8t0P4yfJUJAOq5mjaqAs3bJtCH9hLSO5c9XQNEHSvzkUxs
    8zyN7bOQLQObMxNjycyLZKAdk2r5GOLJl7c2YzJB/29ZEu4UCV+9ySXHkywedhv9XRlKwT
    K9+e2etVeRN7JOkCPOGssQH43uVt9ZW+Hntp7KN3pQ+nk0g3l2tIv5G6bF7EjBC8kpI6De
    0FfBlrrnoz4Ub7w5iP1fXjFwWzZECuX2CLTrW7ppgKXH8a0M/tq6V4PO5Lwk+j54EsYxlt
    mEIjuVEDTdK2Bh3fVNaaclwIU3JVc9xKlBZO6TytC1AsZvUlWQ9JCIk6BSy/BsNGAciq7X
    huOKEe5jodINDwo0oxAAABACBYoQDqtp0JsHd00MVkT/riMfnNbA3EEtcR+vP3csE564iZ
    m/WZcA7Y7gqi0gKQ/TOmRpKrBWdFJkrtJuPytTcPjaezU0ne3tvahKQnuiVi1o6o03RHjM
    v6xXiXWQk3USN+IJ3Jr2S85J+OtoON9nN3ZL/jH+pv9Hg6UAY7gIsP1jf7YB2E7ZlEV5hr
    1+46ZQ/yAuQr2nXX37nRK2AC8jBP+K3pC08SqNQaG+j5uwLpiARXlyq0gKqfjq+K/B9gJT
    maGorK17LZ4rFREKNbn0LfW4uMrUUYsxY7bJI3nQfKyXnhp6zeXXKPHTKwvZxFBEBDCI3R
    w9CuJh02ogzyKZQAAAEBAPbXM74XMyhGJAJbePxcQvNys6+o9oXXP8PUwC8CoSKPyhH6s4
    P5MkB1CuZZAX9En1gjE8vOvPAbiqAQ5A2pxzmoafJUcR3/53uRCSHnZfiuyYa1+xAHlvKE
    Pj7aaaAcNav3O7MDl1l9SvPOGobsOnPOQF0bP8vzJMIyF55LJn2tHiZfg9cZ2eb708QKjO
    vujrtlSQIuP6HdJY/ooQbujts0kR9XTmLg+Ag8RiHiPcjAp1qZk0Hr4n2PXczXg07ZyQ3Z
    J+vBu0B1snJMi+pwHNujfHqumPLz3snHSFPQJYuOWonwSwcdQy2ZlyCCZdRLVJo6OPYfQA
    0/tuYPRAIe2xkAAAEBAOFx01GkvSMGtj1sSsTV+pG+9EsaI1/sBgi+TiZnxyuPPvIj4Rdv
    SaHI8GbEYdeNzObfmgzxs6kij8EC7ExuE9442aXyxm8HMQpZsrJyI3tcgA4fHybgrhqpDD
    TBpA59Gc3lJOC/COO5ZRzBmNLwGpA4Uuw3kJDsXxhYXGaFMluo5jEERy/LPjbdxP4VPBZ4
    86EWpIUC5c9sc+K/qRtnYjI+jaUzZEq574DYxOlH3dNGV2d/gclIBqL2cSFQ5kZjlqrQpH
    DxHQsAjKp8b8r8L45uroE/BmcC2H6J77Yjk0cExOgJo9JZ6fLtSVXxmd4c/lyQhIT2m443
    ID913ay5/lMAAAAJQ0FfY295b3RlAQI=
    -----END OPENSSH PRIVATE KEY-----

kind: ConfigMap
metadata:
  name: f7t-ca-ssh-keys
  namespace: {{ .Values.namespace }}
