apiVersion: v1
data:
  f7t-ssl.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIJKQIBAAKCAgEAnp+NF3DHkYIP+JfHmxhrHpvaR9rK9cwgcbqZLF14p1jZkSob
    KrSYlQpTvqTQvMAhBdrnUks6b5oSFV+gRO+a0gFW9TwKYKHc9zZaha8jlYtzgx8U
    phh5HSzaiG90bZDWXAkByQ4XvRAMjgUU1rVlCYHGjx8Kv03BPw03hE5mG2wuuKpq
    H/CYI57pN1FW5HkabQiJLMqpWJri6zy/oFPtbN9XJK1dqfW/MRo2Z24C/ARlNLce
    Y3WUMHbogqNnpC4+Yy4Z6xg5ZlemIDgeNejtPp5arLTk+uHWwmnA4q/yZRfDeaWX
    WISsZD461ExLc/Y/MCNlXn8pnSYHlmss7IXp5BaTe4IfvFjGsx3wBjWZIUObI1tx
    A4rakxLCUHmca7OiZD32S5BJqNz7X8Ki9ZFujHwHl9tgFEUZk0483+P+heTqkhyu
    N50WAq4+qLzv61dOLNdS8SZHWxIEW9gL9G28WzPBKbgARnZUhPj9NoVgMmVjJvE8
    mVb3SoA1uJc04WOTkJpAYDhGFBZ8kBt3jUBk5Cs7Or2+RtQ7YKVKD79yEe7MHkGK
    xOwes5/7XULgO05LTM8Ft6MWkU542tT2V9psAX9kasvieLISOgXMeTrgxlqQAREB
    2wKD9uD1CDoeef763t5cYswHG+VBMVey6lg3+uU/EA5F9292nSDmax+EiLMCAwEA
    AQKCAgBBWOuwR3b/+/wGZskFnRasQnq3dWx9vH11PPFTdKJ7FsBy7EzK2CGv7NQ5
    Sv7vc5tnJRp9LZ7CUU+33HBTVf6LG6AuYXDJBIXallrOjitztUJ+NzSzhIuIuGzD
    Hl9xr+SPf+prYNHowo7Zh0Bhf9NDCmK5nYk47Jh7GD/R0tZ/356T1yjnRZ/3tMTR
    VEIe18FKP+T7PfZsGUr4rEspisnaO1xUMNPQa/w7B1h4Xbr/BfSHthTf1pWZLbN1
    9kmBOsfa5igpUQ58mglHZrcTcIUkcepbEh7vOFDYQOcEvIV4nkSafdyOzAGVPonP
    4iqHeF/pvftJ5ctIAV3I2xhjzHthJK4M/TR9h7DZSST/XLJ6H/oBjn+76oi8GLBV
    oY0eZCHZ0EOV/ZVg2zWRoNYWcuvb5keGH6PLalcTmyBOR3ylfC8X2UxY/NuaYxuE
    h+grQkeMkk19CFRL5Bw1pG64LTxaid84RJ0Y2mevF4k2kNmTZHpkt832MGUB1iS4
    V1YgoRvgm+FHGEApa7otXFLZd96W/12QXSt+rhhLYtemQXqS4aDRyjYSm/kjHlj8
    WFGoFNHDlnCW0t+ybSfag0JpUHQcYgkGff8B4pw4l4q96124P5JXdNncGFkRbUTH
    +RfklJGRIExfRdiN+bS0BDlvEZ0bZWIItHtzysSUdS4oIPn9kQKCAQEA02Q727C0
    WJ9tFfMRygq+0IVEO13qEbQOvkl5s7J9Vl679Bn3KwHBG4rS3tQRBkFzikP4apBx
    B8jOCPvvNihSnOj1f0uX31C6NxYdyazWH/CW4OwE8Tq0sgx3MPshUVEswMVvIQQv
    v4mo6ynoM83nu1x2jj7sJ6Pc6nQR37Uc45kc+UQF5RdU80M95p8MyO1LsGuhyuJK
    e66IRg28+Zl0MHW7+JzG7RGikuoIIFNz4UgJ8w0cdIP0Iq5FVReQl0Myu2IDgxH1
    nbwPyB3oglaJPsM1yzkHoNd//CHutt1CKnPDOXBddI4EmrKvJRGR/YBwD59ICKBU
    HR/11PF8pjnZmQKCAQEAwBis73B0vvsu6iCLdYrGD7bvNg9qp3aJoFUDeLcPxqIz
    hMboZVzbITYsGHHMIyhUbDCG/rUdz1TA41N+BGgUHbiogsImlwggrrQvZizbG3s3
    ylR1WD4r4nwcNcX6kLovq5BOz7YIU0j0KgpbQsAAU3pdkgr16qgW0yVi04q6mUCI
    2ftsgY5J57+JHtYdR6ZVNOCI2d3WCw4urKKwMjTGs/7fQ76Q1N5n19heXgxkJYL/
    Hn51biwCGNp8+AsvksFfNeRNmRLPZJIiu8vtGfDYY8o5ZIzOZGJKScG6BbneNofU
    3RZtfPJkzYD7C18Gw0MRQPbB4eYmVuopBRpJeqpcKwKCAQEAoC00OhxkGz76ToZ3
    NUv9GE3SzNU1tqJkBYXxRNt7o4V3D9jY8+qJY5BGhnfUSpQvs1YblsvKCeb7T81u
    je/x4VmYJBOoiZtG7tTAT3+6ZEtOWDIe8JbWMo/FhQTVUyOaMJupwC/G6nCp4T9I
    5nAgJlVCtDgzgznj/Hdkz8kRkdgEH1CO0u9h/E44Sla8PkeocY6s8umTHLK8KbDh
    P5QqeUnM2+4Xwaz6Li5NaAk0JkEK4PNPW25dACZi/L41XpiZiWkUVi22mgXVQ4J+
    Grztk/Qg/9M/131TSj5//mobZ8V96TkeZ2HxVTMOCZ2NrLO0tfGwiHDMK6F7ChbN
    p7rwCQKCAQEAmsEGSNtC4jy/XdScJTSIPU61xcqDtKeVVjpG0rA/oFk5weTwggBd
    dJMM0SCUQVqTMJmjl3zXqBjyT/EKW4hxdEQ4VScOKaxdkAEPEnRei/QnTPPfmRh1
    CD/OBjAZnRCxqLhYFZPjfx0NvvSa8tp1KMsyqJ314XZK9Q1wYVWo4B+SYHHhxzmX
    JoEyeUorSnagvDmLZmEFt+BUD7X81mWYEpfoy82xJhyKceQYmhHHeEThPHLKLdh8
    VANom/d++u6XwnXLYd86fx4Pp1UxDS3vVe0rcWrSNyLMEEFmmIhVkX66KOaRjBBG
    zxvyowWKEDJuqvRf25orFugL5dV4jr7CAwKCAQBIBH7XihI+Ko/P9ajsSc9f84I8
    IEuefqYkCbMim8XKbe7gcsbjj62PjHf4B7dJGSzkQv75/4gT2/6Z0UZd3oC/1XDU
    19I0Cqamx8Ud/ec0GZY0zWyW4Yvx47C+r0Bcq2CURhNMhLiDRvDSmXokR9fIMZSi
    A/GIWwc532z0iPA5i2+9nRz1zSkbRXS7qlQTFufu09+b7m8u7F38B1unV0fzBLdY
    tRlYZdSVjkreH1pYKtY2+uTvpHQEA7YTUcXQfto5wACf9ltr6Xd2YISlqGgvVadA
    9szPeA0rbJLWzRYKso8d7SnMC6rPl5umOoYUM1iG75yc5J+nwkBv+z0c8J34
    -----END RSA PRIVATE KEY-----
kind: ConfigMap
metadata:
  name: f7t-ssl-key
  namespace: {{ .Values.namespace }}
