apiVersion: v1
data:
  user-key.pub: |
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDEDvgDXtHRf88VaThzNz2MtPk7Ux81ZJ/isUgfW6D5C test1@cluster
kind: ConfigMap
metadata:
  name: f7t-user-ssh-pub-keys
  namespace: {{ .Values.namespace }}