##
##  Copyright (c) 2019-2021, ETH Zurich. All rights reserved.
##
##  Please, refer to the LICENSE file in the root directory.
##  SPDX-License-Identifier: BSD-3-Clause
##
- name: create build directory
  file:
    path: /home/firecrest/awx-firecrest-build
    state: directory
    owner: firecrest
    group: firecrest
    mode: "0755"

- name: Clone firecrest git repository
  git:
    repo: "https://github.com/eth-cscs/firecrest.git"
    dest: /home/firecrest/awx-firecrest-build
    version: "{{ commit_id }}"

- name: Build base image with build tag 
  docker_image:
    name: "localhost:5000/f7t-base:{{ build_tag }}"
    build:
      path: /home/firecrest/awx-firecrest-build
      dockerfile: ./deploy/docker/base/Dockerfile
      pull: yes
    source: build
    state: present
    push: yes

# TODO: Building because tagging didn't seem to be properly tagging
- name: Build base image with latest tag 
  docker_image:
    name: "localhost:5000/f7t-base:latest"
    build:
      path: /home/firecrest/awx-firecrest-build
      dockerfile: ./deploy/docker/base/Dockerfile
      pull: yes
    source: build
    state: present
    push: yes

- name: Build base image locally 
  docker_image:
    name: "f7t-base"
    build:
      path: /home/firecrest/awx-firecrest-build
      dockerfile: ./deploy/docker/base/Dockerfile
      pull: yes
    source: build
    state: present

- name: Build container image
  docker_image:
    name: "localhost:5000/{{ item.key }}:{{ build_tag }}"
    build:
      path: /home/firecrest/awx-firecrest-build
      dockerfile: ./deploy/docker/{{ item.key }}/Dockerfile
      # Pull no, because base image is built locally for now
      pull: no
    source: build
    state: present
    push: yes
  with_dict: "{{ image_definitions }}"

- name: Build certificator image
  docker_image:
    name: "localhost:5000/certificator:{{ build_tag }}"
    build:
      path: /home/firecrest/awx-firecrest-build
      dockerfile: ./deploy/docker/certificator/Dockerfile
    source: build
    state: present
    push: yes  

- name: build client image
  docker_image:
    name: "localhost:5000/client:{{ build_tag }}"
    build:
      path: /home/firecrest/awx-firecrest-build/src/tests/template_client
      dockerfile: ./Dockerfile
      pull: yes
    source: build
    state: present
    push: yes

- name: Pull redis and push to local registry
  docker_image:
    name: redis:5
    repository: "localhost:5000/taskpersistence:{{ build_tag }}"
    push: yes
    source: pull

